"""
Picks Portfolio Manager - Automated paper trading for ML-generated stock picks.

This module manages a dedicated Alpaca paper trading portfolio that automatically
executes buy/sell orders for picks generated by the ensemble picker.

Features:
- Position entry with market orders
- Automatic stop-loss orders
- Position monitoring and tracking
- Performance analytics
- Order validation and risk management
"""

import os
import logging
from datetime import datetime, date
from typing import List, Dict, Optional
import pandas as pd

logger = logging.getLogger(__name__)


class PicksPortfolioManager:
    """Manage automated paper trading portfolio for stock picks."""
    
    def __init__(
        self,
        capital: float = 10000.0,
        alpaca_key: Optional[str] = None,
        alpaca_secret: Optional[str] = None
    ):
        """
        Initialize portfolio manager.
        
        Args:
            capital: Total portfolio capital (default: $10,000)
            alpaca_key: Alpaca API key (uses ALPACA_KEY_PICKS env var if None)
            alpaca_secret: Alpaca secret key (uses ALPACA_SECRET_PICKS env var if None)
        """
        # Try to import Alpaca 2 keys from ai_picks_portfolio
        try:
            from financial_dashboard.tabs.ai_picks_portfolio import ALPACA2_KEY, ALPACA2_SECRET
        except ImportError:
            ALPACA2_KEY = None
            ALPACA2_SECRET = None

        self.capital = capital
        self.alpaca_key = alpaca_key or ALPACA2_KEY or os.getenv('ALPACA2_KEY') or os.getenv('ALPACA_KEY_PICKS') or os.getenv('APCA_API_KEY_ID')
        self.alpaca_secret = alpaca_secret or ALPACA2_SECRET or os.getenv('ALPACA2_SECRET') or os.getenv('ALPACA_SECRET_PICKS') or os.getenv('APCA_API_SECRET_KEY')
        
        # Initialize Alpaca client
        self.alpaca_client = None
        self._initialize_alpaca()
        
        logger.info(f"✓ Portfolio Manager initialized with ${capital:,.2f} capital")
    
    def _initialize_alpaca(self):
        """Initialize Alpaca API client."""
        try:
            from alpaca.trading.client import TradingClient
            
            if not self.alpaca_key or not self.alpaca_secret:
                logger.warning("⚠️ Alpaca credentials not found. Paper trading disabled.")
                logger.warning("Set ALPACA_KEY_PICKS and ALPACA_SECRET_PICKS environment variables")
                return
            
            self.alpaca_client = TradingClient(
                api_key=self.alpaca_key,
                secret_key=self.alpaca_secret,
                paper=True  # Always use paper trading
            )
            
            # Test connection
            account = self.alpaca_client.get_account()
            logger.info(f"✓ Connected to Alpaca paper account: ${float(account.cash):,.2f} cash")
            
        except ImportError:
            logger.error("⚠️ alpaca-py not installed. Install with: pip install alpaca-py")
        except Exception as e:
            logger.error(f"Failed to initialize Alpaca client: {e}")
    
    def deploy_picks(
        self,
        picks_df: pd.DataFrame,
        position_size_pct: float = 5.0,
        stop_loss_pct: float = -10.0,
        take_profit_pct: float = 20.0
    ) -> Dict:
        """
        Deploy selected picks to portfolio by placing market orders.
        
        Args:
            picks_df: DataFrame with picks to deploy (must have 'ticker' column)
            position_size_pct: Position size as % of capital (default: 5%)
            stop_loss_pct: Stop loss % (default: -10%)
            take_profit_pct: Take profit % (default: +20%)
            
        Returns:
            Dict with deployment results
        """
        if self.alpaca_client is None:
            return {
                'status': 'error',
                'message': 'Alpaca not connected',
                'deployed': 0
            }
        
        try:
            from alpaca.trading.requests import MarketOrderRequest, StopOrderRequest
            from alpaca.trading.enums import OrderSide, TimeInForce
            
            deployed = []
            failed = []
            
            # Get current cash
            account = self.alpaca_client.get_account()
            available_cash = float(account.cash)
            
            # Calculate position size in dollars
            position_size_dollars = (position_size_pct / 100) * self.capital
            
            for _, pick in picks_df.iterrows():
                ticker = pick['ticker']
                
                try:
                    # Get current price
                    try:
                        from alpaca.data.historical import StockHistoricalDataClient
                        from alpaca.data.requests import StockLatestQuoteRequest
                        
                        data_client = StockHistoricalDataClient(
                            self.alpaca_key,
                            self.alpaca_secret
                        )
                        
                        quote_request = StockLatestQuoteRequest(symbol_or_symbols=ticker)
                        quote = data_client.get_stock_latest_quote(quote_request)[ticker]
                        current_price = float(quote.ask_price) or float(quote.bid_price)
                        
                    except:
                        # Fallback to yfinance
                        import yfinance as yf
                        stock = yf.Ticker(ticker)
                        current_price = stock.info.get('currentPrice') or stock.info.get('regularMarketPrice')
                    
                    if not current_price or current_price <= 0:
                        failed.append({'ticker': ticker, 'reason': 'Invalid price'})
                        continue
                    
                    # Calculate quantity
                    quantity = int(position_size_dollars / current_price)
                    
                    if quantity == 0:
                        failed.append({'ticker': ticker, 'reason': 'Quantity too small'})
                        continue
                    
                    # Check if we have enough cash
                    cost = quantity * current_price
                    if cost > available_cash:
                        failed.append({'ticker': ticker, 'reason': 'Insufficient cash'})
                        continue
                    
                    # Place market buy order
                    market_order_data = MarketOrderRequest(
                        symbol=ticker,
                        qty=quantity,
                        side=OrderSide.BUY,
                        time_in_force=TimeInForce.DAY
                    )
                    
                    order = self.alpaca_client.submit_order(market_order_data)
                    
                    # Calculate stop-loss and take-profit prices
                    stop_price = current_price * (1 + stop_loss_pct / 100)
                    take_profit_price = current_price * (1 + take_profit_pct / 100)
                    
                    # TODO: Place stop-loss order after market order fills
                    # This requires checking order status and waiting for fill
                    
                    deployed.append({
                        'ticker': ticker,
                        'quantity': quantity,
                        'entry_price': current_price,
                        'order_id': order.id,
                        'stop_loss': stop_price,
                        'take_profit': take_profit_price
                    })
                    
                    # Update available cash
                    available_cash -= cost
                    
                    logger.info(f"✓ Deployed {ticker}: {quantity} shares @ ${current_price:.2f}")
                    
                except Exception as e:
                    logger.error(f"Failed to deploy {ticker}: {e}")
                    failed.append({'ticker': ticker, 'reason': str(e)})
            
            return {
                'status': 'success',
                'deployed': len(deployed),
                'failed': len(failed),
                'positions': deployed,
                'errors': failed
            }
            
        except Exception as e:
            logger.exception(f"Error deploying picks: {e}")
            return {
                'status': 'error',
                'message': str(e),
                'deployed': 0
            }
    
    def get_positions(self) -> pd.DataFrame:
        """
        Get current positions from Alpaca.
        
        Returns:
            DataFrame with position details
        """
        if self.alpaca_client is None:
            return pd.DataFrame()
        
        try:
            positions = self.alpaca_client.get_all_positions()
            
            if not positions:
                return pd.DataFrame()
            
            # Convert to DataFrame
            data = []
            for pos in positions:
                data.append({
                    'ticker': pos.symbol,
                    'quantity': int(float(pos.qty)),  # Alpaca returns decimal strings
                    'entry_price': float(pos.avg_entry_price),
                    'current_price': float(pos.current_price),
                    'market_value': float(pos.market_value),
                    'cost_basis': float(pos.cost_basis),
                    'unrealized_pl': float(pos.unrealized_pl),
                    'unrealized_plpc': float(pos.unrealized_plpc) * 100,  # Convert to %
                    'side': pos.side
                })
            
            df = pd.DataFrame(data)
            return df
            
        except Exception as e:
            logger.error(f"Failed to get positions: {e}")
            return pd.DataFrame()
    
    def close_position(self, ticker: str) -> Dict:
        """
        Close a position by selling all shares.
        
        Args:
            ticker: Ticker symbol to close
            
        Returns:
            Dict with close result
        """
        if self.alpaca_client is None:
            return {'status': 'error', 'message': 'Alpaca not connected'}
        
        try:
            from alpaca.trading.requests import MarketOrderRequest
            from alpaca.trading.enums import OrderSide, TimeInForce
            
            # Get position
            position = self.alpaca_client.get_open_position(ticker)
            
            if not position:
                return {'status': 'error', 'message': f'No position found for {ticker}'}
            
            # Place market sell order
            market_order_data = MarketOrderRequest(
                symbol=ticker,
                qty=abs(int(position.qty)),
                side=OrderSide.SELL,
                time_in_force=TimeInForce.DAY
            )
            
            order = self.alpaca_client.submit_order(market_order_data)
            
            logger.info(f"✓ Closed position {ticker}: {position.qty} shares")
            
            return {
                'status': 'success',
                'ticker': ticker,
                'quantity': int(position.qty),
                'order_id': order.id
            }
            
        except Exception as e:
            logger.error(f"Failed to close position {ticker}: {e}")
            return {'status': 'error', 'message': str(e)}
    
    def close_all_positions(self) -> Dict:
        """
        Close all open positions.
        
        Returns:
            Dict with results
        """
        if self.alpaca_client is None:
            return {'status': 'error', 'message': 'Alpaca not connected'}
        
        try:
            # Cancel all orders first
            self.alpaca_client.cancel_orders()
            
            # Close all positions
            self.alpaca_client.close_all_positions(cancel_orders=True)
            
            logger.info("✓ Closed all positions")
            
            return {
                'status': 'success',
                'message': 'All positions closed'
            }
            
        except Exception as e:
            logger.error(f"Failed to close all positions: {e}")
            return {'status': 'error', 'message': str(e)}
    
    def get_account_info(self) -> Dict:
        """
        Get account information.
        
        Returns:
            Dict with account details
        """
        if self.alpaca_client is None:
            return {
                'total_value': 0,
                'cash': 0,
                'equity': 0,
                'buying_power': 0
            }
        
        try:
            account = self.alpaca_client.get_account()
            
            return {
                'total_value': float(account.portfolio_value),
                'cash': float(account.cash),
                'equity': float(account.equity),
                'buying_power': float(account.buying_power),
                'day_trades': int(account.daytrade_count) if hasattr(account, 'daytrade_count') else 0
            }
            
        except Exception as e:
            logger.error(f"Failed to get account info: {e}")
            return {
                'total_value': 0,
                'cash': 0,
                'equity': 0,
                'buying_power': 0
            }
    
    def get_orders(self, limit: int = 100) -> pd.DataFrame:
        """
        Get recent orders.
        
        Args:
            limit: Max number of orders to return
            
        Returns:
            DataFrame with order history
        """
        if self.alpaca_client is None:
            return pd.DataFrame()
        
        try:
            from alpaca.trading.requests import GetOrdersRequest
            from alpaca.trading.enums import QueryOrderStatus
            
            request = GetOrdersRequest(
                status=QueryOrderStatus.ALL,
                limit=limit
            )
            
            orders = self.alpaca_client.get_orders(filter=request)
            
            if not orders:
                return pd.DataFrame()
            
            # Convert to DataFrame
            data = []
            for order in orders:
                data.append({
                    'date': order.created_at,
                    'ticker': order.symbol,
                    'side': order.side,
                    'quantity': int(float(order.qty)) if order.qty else 0,  # Alpaca returns decimal strings
                    'filled_qty': int(float(order.filled_qty)) if order.filled_qty else 0,
                    'type': order.type,
                    'status': order.status,
                    'filled_price': float(order.filled_avg_price) if order.filled_avg_price else None
                })
            
            df = pd.DataFrame(data)
            return df
            
        except Exception as e:
            logger.error(f"Failed to get orders: {e}")
            return pd.DataFrame()
