"""
Alpaca Options Lab - Strategy Base Class

Abstract base class for all trading strategies with:
- Lifecycle hooks (start, stop, market data, fills)
- Configuration management
- Signal generation
- Risk limit integration
- Helper methods for common operations

Usage:
    from src.strategies import Strategy, StrategyConfig
    
    @StrategyRegistry.register("my_strategy")
    class MyStrategy(Strategy):
        def on_start(self) -> None:
            self.state['initialized'] = True
        
        def on_market_data(self, event: MarketEvent) -> List[Signal]:
            # Generate trading signals
            return []
        
        def on_order_fill(self, fill: FillEvent) -> None:
            # Handle fills
            pass
        
        def on_position_update(self, position: OptionPosition) -> None:
            # React to position changes
            pass
        
        def on_stop(self) -> Dict[str, Any]:
            return {'stats': self.state}
"""
from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Callable, Dict, List, Optional, TYPE_CHECKING
import yaml

from src.utils.logging_config import get_logger
from src.utils.exceptions import RiskLimitError, StrategyError

if TYPE_CHECKING:
    from src.strategies.context import StrategyContext
    from src.lifecycle.fsm import Position

logger = get_logger(__name__)


class SignalType(Enum):
    """Type of trading signal."""
    ENTRY = "entry"
    EXIT = "exit"
    ADJUSTMENT = "adjustment"
    ROLL = "roll"


class OrderSide(Enum):
    """Order side."""
    BUY = "buy"
    SELL = "sell"


@dataclass
class OrderLeg:
    """Single leg of a multi-leg order."""
    contract_id: int
    symbol: str
    side: OrderSide
    quantity: int
    price: Optional[float] = None  # None for market orders
    
    def __post_init__(self):
        if isinstance(self.side, str):
            self.side = OrderSide(self.side)


@dataclass
class Signal:
    """
    Trading signal generated by a strategy.
    
    Signals represent trade intentions that will be validated
    and executed by the order management system.
    """
    strategy: str
    signal_type: SignalType
    legs: List[OrderLeg]
    entry_reason: str
    expected_credit: Optional[float] = None  # For credit spreads
    expected_debit: Optional[float] = None   # For debit spreads
    max_risk: Optional[float] = None
    target_profit: Optional[float] = None
    stop_loss: Optional[float] = None
    metadata: Dict[str, Any] = field(default_factory=dict)
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    correlation_id: str = ""
    
    def __post_init__(self):
        if isinstance(self.signal_type, str):
            self.signal_type = SignalType(self.signal_type)
        if not self.correlation_id:
            import uuid
            self.correlation_id = str(uuid.uuid4())[:8]
    
    @property
    def is_credit_spread(self) -> bool:
        """Check if this is a credit-generating trade."""
        return self.expected_credit is not None and self.expected_credit > 0
    
    @property
    def net_contracts(self) -> int:
        """Net contract exposure."""
        return sum(
            leg.quantity if leg.side == OrderSide.BUY else -leg.quantity
            for leg in self.legs
        )


@dataclass
class StrategyConfig:
    """
    Strategy configuration.
    
    Loaded from YAML files for easy modification without code changes.
    """
    name: str
    enabled: bool = True
    capital_allocation: float = 0.1  # 10% of portfolio
    max_positions: int = 10
    max_daily_trades: int = 50
    risk_limits: Dict[str, float] = field(default_factory=dict)
    parameters: Dict[str, Any] = field(default_factory=dict)
    description: str = ""
    version: str = "1.0.0"
    
    def __post_init__(self):
        # Set default risk limits if not provided
        if not self.risk_limits:
            self.risk_limits = {
                'max_delta': 100.0,
                'max_gamma': 50.0,
                'max_vega': 1000.0,
                'max_theta': -500.0,
                'max_loss_per_trade': 0.02,  # 2% of allocated capital
                'max_daily_loss': 0.05,       # 5% of allocated capital
            }
    
    @classmethod
    def from_yaml(cls, path: str) -> 'StrategyConfig':
        """Load configuration from YAML file."""
        try:
            with open(path, 'r') as f:
                data = yaml.safe_load(f)
            return cls(**data)
        except Exception as e:
            logger.error("failed_to_load_strategy_config", path=path, error=str(e))
            raise StrategyError(f"Failed to load strategy config: {e}")
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'StrategyConfig':
        """Create from dictionary."""
        return cls(**data)
    
    def to_yaml(self, path: str) -> None:
        """Save configuration to YAML file."""
        data = {
            'name': self.name,
            'enabled': self.enabled,
            'capital_allocation': self.capital_allocation,
            'max_positions': self.max_positions,
            'max_daily_trades': self.max_daily_trades,
            'risk_limits': self.risk_limits,
            'parameters': self.parameters,
            'description': self.description,
            'version': self.version,
        }
        with open(path, 'w') as f:
            yaml.dump(data, f, default_flow_style=False)
    
    def validate(self) -> bool:
        """Validate configuration."""
        if not self.name:
            raise ValueError("Strategy name is required")
        if not 0 < self.capital_allocation <= 1:
            raise ValueError("capital_allocation must be between 0 and 1")
        if self.max_positions < 1:
            raise ValueError("max_positions must be at least 1")
        return True


@dataclass
class MarketEvent:
    """Market data event."""
    timestamp: datetime
    symbol: str
    underlying: str
    bid: float
    ask: float
    last: float
    volume: int
    open_interest: int = 0
    iv: Optional[float] = None
    greeks: Optional[Dict[str, float]] = None
    correlation_id: str = ""
    
    @property
    def mid(self) -> float:
        """Mid price."""
        return (self.bid + self.ask) / 2
    
    @property
    def spread(self) -> float:
        """Bid-ask spread."""
        return self.ask - self.bid
    
    @property
    def spread_pct(self) -> float:
        """Spread as percentage of mid."""
        mid = self.mid
        return self.spread / mid if mid > 0 else 0


@dataclass
class FillEvent:
    """Order fill event."""
    order_id: str
    strategy: str
    symbol: str
    side: OrderSide
    quantity: int
    fill_price: float
    commission: float
    timestamp: datetime
    correlation_id: str = ""


class Strategy(ABC):
    """
    Abstract base class for trading strategies.
    
    Lifecycle:
    1. __init__() - Constructor with config and context
    2. on_start() - Initialize strategy state
    3. on_market_data() - Process each tick/bar (called repeatedly)
    4. on_order_fill() - Handle order executions
    5. on_position_update() - React to position changes
    6. on_stop() - Cleanup and final reporting
    
    Subclasses must implement all abstract methods.
    Helper methods provide common functionality.
    """
    
    def __init__(self, config: StrategyConfig, context: 'StrategyContext'):
        """
        Initialize strategy.
        
        Args:
            config: Strategy configuration
            context: Execution context with system access
        """
        self.config = config
        self.context = context
        self.state: Dict[str, Any] = {}
        self._started = False
        self._stopped = False
        self._daily_trades = 0
        self._daily_pnl = 0.0
        self._last_trade_date: Optional[datetime] = None
        
        # Validate config
        config.validate()
        
        logger.info(
            "strategy_initialized",
            name=config.name,
            allocation=config.capital_allocation,
            max_positions=config.max_positions
        )
    
    # ================================================================
    # Abstract Methods - Must be implemented by subclasses
    # ================================================================
    
    @abstractmethod
    def on_start(self) -> None:
        """
        Called once when strategy starts.
        
        Initialize any strategy-specific state here.
        This is called before any market data is processed.
        """
        pass
    
    @abstractmethod
    def on_market_data(self, event: MarketEvent) -> List[Signal]:
        """
        Process market data and generate signals.
        
        Called for each market data event. Should be efficient
        as it may be called thousands of times per second.
        
        Args:
            event: Market data event
            
        Returns:
            List of Signal objects (can be empty)
        """
        pass
    
    @abstractmethod
    def on_order_fill(self, fill: FillEvent) -> None:
        """
        Handle order execution.
        
        Called when an order is filled. Use this to update
        strategy state and track positions.
        
        Args:
            fill: Fill event with execution details
        """
        pass
    
    @abstractmethod
    def on_position_update(self, position: 'Position') -> None:
        """
        React to position state changes.
        
        Called when a position's state changes (e.g., opened,
        partially closed, assigned). Use for position management.
        
        Args:
            position: Updated position object
        """
        pass
    
    @abstractmethod
    def on_stop(self) -> Dict[str, Any]:
        """
        Cleanup and return final statistics.
        
        Called when strategy is stopped. Return a dictionary
        with performance metrics and state summary.
        
        Returns:
            Dictionary with strategy metrics
        """
        pass
    
    # ================================================================
    # Helper Methods - Available to all strategies
    # ================================================================
    
    def get_portfolio_greeks(self) -> Dict[str, float]:
        """Get current portfolio Greeks."""
        return self.context.get_portfolio_greeks()
    
    def get_open_positions(self) -> List['Position']:
        """Get all open positions for this strategy."""
        return self.context.get_positions(strategy=self.config.name)
    
    def get_allocated_capital(self) -> float:
        """Get capital allocated to this strategy."""
        return self.context.get_portfolio_value() * self.config.capital_allocation
    
    def get_available_capital(self) -> float:
        """Get available (unused) capital for this strategy."""
        positions = self.get_open_positions()
        used_capital = sum(abs(p.market_value) for p in positions)
        return self.get_allocated_capital() - used_capital
    
    def check_risk_limits(self, signal: Signal) -> bool:
        """
        Check if signal would breach risk limits.
        
        Args:
            signal: Proposed signal
            
        Returns:
            True if within limits, False otherwise
        """
        return self.context.check_risk_limits(signal, self.config.risk_limits)
    
    def can_trade(self) -> bool:
        """Check if strategy can place new trades."""
        # Check if enabled
        if not self.config.enabled:
            return False
        
        # Check daily trade limit
        today = datetime.now(timezone.utc).date()
        if self._last_trade_date != today:
            self._daily_trades = 0
            self._daily_pnl = 0.0
            self._last_trade_date = today
        
        if self._daily_trades >= self.config.max_daily_trades:
            logger.warning(
                "daily_trade_limit_reached",
                strategy=self.config.name,
                limit=self.config.max_daily_trades
            )
            return False
        
        # Check daily loss limit
        max_daily_loss = self.config.risk_limits.get('max_daily_loss', 0.05)
        if self._daily_pnl < -self.get_allocated_capital() * max_daily_loss:
            logger.warning(
                "daily_loss_limit_reached",
                strategy=self.config.name,
                daily_pnl=self._daily_pnl
            )
            return False
        
        # Check position limit
        if len(self.get_open_positions()) >= self.config.max_positions:
            logger.debug(
                "max_positions_reached",
                strategy=self.config.name,
                max_positions=self.config.max_positions
            )
            return False
        
        return True
    
    def submit_signal(self, signal: Signal) -> Optional[str]:
        """
        Submit signal for execution.
        
        Performs risk checks before submission.
        
        Args:
            signal: Trading signal
            
        Returns:
            Order ID if accepted, None if rejected
        """
        if not self.can_trade():
            return None
        
        if not self.check_risk_limits(signal):
            logger.warning(
                "signal_rejected_risk_limits",
                strategy=self.config.name,
                signal=signal.correlation_id
            )
            return None
        
        try:
            order_id = self.context.submit_signal(signal)
            self._daily_trades += 1
            
            logger.info(
                "signal_submitted",
                strategy=self.config.name,
                order_id=order_id,
                signal_type=signal.signal_type.value
            )
            
            return order_id
            
        except Exception as e:
            logger.error(
                "signal_submission_failed",
                strategy=self.config.name,
                error=str(e)
            )
            return None
    
    def record_pnl(self, pnl: float) -> None:
        """Record P&L for daily tracking."""
        self._daily_pnl += pnl
    
    # ================================================================
    # Internal Methods
    # ================================================================
    
    def _start(self) -> None:
        """Internal start method."""
        if self._started:
            return
        
        self._started = True
        self.on_start()
        
        logger.info("strategy_started", name=self.config.name)
    
    def _stop(self) -> Dict[str, Any]:
        """Internal stop method."""
        if self._stopped:
            return {}
        
        self._stopped = True
        result = self.on_stop()
        
        logger.info(
            "strategy_stopped",
            name=self.config.name,
            daily_trades=self._daily_trades,
            daily_pnl=self._daily_pnl
        )
        
        return result
