apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: alpaca-options

resources:
  - infrastructure.yaml
  - services.yaml
  - networking.yaml
  - monitoring.yaml

commonLabels:
  app.kubernetes.io/name: alpaca-options-lab
  app.kubernetes.io/managed-by: kustomize

configMapGenerator:
  - name: alpaca-options-config
    behavior: merge
    literals:
      - ENVIRONMENT=production
