#!/usr/bin/env python3
"""
Generate mock market_brief.json for Portfolio Positions tab testing.
Creates synthetic market trends signals for all portfolio tickers.
"""

import json
import os
import sys
import random
from datetime import datetime
from pathlib import Path

# Add financial_dashboard to path
sys.path.insert(0, '/app/financial_dashboard')

def generate_market_brief(tickers, output_path=None):
    """Generate market_brief.json with synthetic data for given tickers."""
    
    if output_path is None:
        output_path = Path('/app/financial_dashboard/cache/market_brief.json')
    else:
        output_path = Path(output_path)
    
    print("=" * 80)
    print("MARKET BRIEF GENERATOR")
    print("=" * 80)
    print(f"Tickers: {len(tickers)}")
    print(f"Output: {output_path}")
    print()
    
    # Generate detailed signals for each ticker
    detailed = []
    
    trend_signals = ['BULLISH', 'BEARISH', 'NEUTRAL']
    
    for ticker in tickers:
        # Generate realistic-looking random values
        momentum = round(random.uniform(-2.0, 2.0), 2)
        sentiment = round(random.uniform(-1.0, 1.0), 2)
        volatility = round(random.uniform(0.1, 3.0), 2)
        
        # Determine signal based on momentum + sentiment
        score = momentum + sentiment
        if score > 0.5:
            signal = 'BULLISH'
        elif score < -0.5:
            signal = 'BEARISH'
        else:
            signal = 'NEUTRAL'
        
        detailed.append({
            'Ticker': ticker,
            'Signal': signal,
            'Momentum': momentum,
            'Sentiment': sentiment,
            'Volatility': volatility,
            'Score': round(score, 2)
        })
        
        print(f"  ✓ {ticker}: {signal} (M={momentum}, S={sentiment}, V={volatility})")
    
    # Create market brief structure
    market_brief = {
        'generated_at': datetime.now().isoformat(),
        'num_tickers': len(tickers),
        'detailed': detailed,
        'summary': {
            'bullish_count': sum(1 for d in detailed if d['Signal'] == 'BULLISH'),
            'bearish_count': sum(1 for d in detailed if d['Signal'] == 'BEARISH'),
            'neutral_count': sum(1 for d in detailed if d['Signal'] == 'NEUTRAL'),
            'avg_momentum': round(sum(d['Momentum'] for d in detailed) / len(detailed), 2),
            'avg_sentiment': round(sum(d['Sentiment'] for d in detailed) / len(detailed), 2),
            'avg_volatility': round(sum(d['Volatility'] for d in detailed) / len(detailed), 2)
        },
        'source': 'mock_generator',
        'note': 'Generated by generate_market_brief.py for testing purposes'
    }
    
    # Ensure output directory exists
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    # Write to file
    with open(output_path, 'w') as f:
        json.dump(market_brief, f, indent=2)
    
    print()
    print("=" * 80)
    print("✅ GENERATION COMPLETE")
    print("=" * 80)
    print(f"File: {output_path}")
    print(f"Size: {output_path.stat().st_size} bytes")
    print()
    print("Summary:")
    print(f"  Bullish: {market_brief['summary']['bullish_count']}")
    print(f"  Bearish: {market_brief['summary']['bearish_count']}")
    print(f"  Neutral: {market_brief['summary']['neutral_count']}")
    print(f"  Avg Momentum: {market_brief['summary']['avg_momentum']}")
    print(f"  Avg Sentiment: {market_brief['summary']['avg_sentiment']}")
    print(f"  Avg Volatility: {market_brief['summary']['avg_volatility']}")
    print()
    
    return market_brief


def main():
    """Main entry point."""
    
    # Load portfolio tickers
    portfolio_path = Path('/app/financial_dashboard/cache/portfolio_data.json')
    
    if portfolio_path.exists():
        with open(portfolio_path, 'r') as f:
            portfolio_data = json.load(f)
        
        tickers = [p['symbol'] for p in portfolio_data.get('positions', [])]
        print(f"✅ Loaded {len(tickers)} tickers from portfolio_data.json")
    else:
        # Default 40 tickers
        tickers = [
            'AAPL', 'AMD', 'APH', 'ARWR', 'ASTS', 'AVAV', 'AVGO', 'BE', 'BEAM', 'CAT',
            'CGON', 'CIFR', 'DIS', 'EA', 'ETSY', 'GEV', 'GLW', 'HOOD', 'HUT', 'INOD',
            'INTC', 'JNJ', 'KLAC', 'LRCX', 'MU', 'NEM', 'ORCL', 'PL', 'PLUG', 'QS',
            'RGTI', 'SMCI', 'SNDK', 'STX', 'SYM', 'TPR', 'TSLA', 'UNH', 'WBD', 'WDC'
        ]
        print(f"⚠️  portfolio_data.json not found - using default {len(tickers)} tickers")
    
    # Generate market brief
    generate_market_brief(tickers)


if __name__ == '__main__':
    main()
